---
platform: linux

image_resource:
  type: docker-image
  source: {repository: jigsheth57/pcfworkshop}

inputs:
  - name: git-repo
  - name: version

outputs:
  - name: build-artifact

run:
  path: git-repo/ci/tasks/build-artifact.sh
