---
platform: linux

image_resource:
  type: docker-image
  source: {repository: jigsheth57/pcfworkshop}

inputs:
  - name: git-repo
  - name: demo-release

run:
  path: git-repo/ci/tasks/cf-deployment.sh

params:
  API_ENDPOINT:
  USERNAME:
  PASSWORD:
  ORG:
  SPACE:
  CF_APPS_DOMAIN:
  CF_APP_NAME:
  CF_ROUTE_NAME:
