---
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/jigsheth57/spring-boot-with-activiti-example.git

- name: version
  type: semver
  source:
    bucket: pcf-workshop-artifacts
    key: activiti-demo-current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

- name: demo-release
  type: s3
  source:
    bucket: ci-pcf-workshop-artifacts
    regexp: activiti-example-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:
- name: unit-test
  public: true
  plan:
  - get: git-repo
    trigger: true
  - task: unit-test
    file: git-repo/ci/tasks/unit-test.yml
    timeout: 15m

- name: build-binary
  public: true
  serial: true
  plan:
  - get: git-repo
    passed: [unit-test]
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-artifact
    file: git-repo/ci/tasks/build-artifact.yml
    timeout: 15m
  - put: demo-release
    params: {file: build-artifact/activiti-example-*.jar}
  - put: version
    params: {file: version/number}

- name: acceptance-tests
  plan:
  - aggregate:
    - get: demo-release
      passed: [build-binary]
      trigger: true
    - get: git-repo
      passed: [build-binary]
      trigger: true
  - task: deploy-to-dev
    file: git-repo/ci/tasks/cf-deployment.yml
    timeout: 15m
    params:
      API_ENDPOINT: {{cf-dev-api}}
      USERNAME: {{cf-dev-username}}
      PASSWORD: {{cf-dev-password}}
      ORG: {{cf-dev-organization}}
      SPACE: {{cf-dev-space}}
      CF_APPS_DOMAIN: {{cf-dev-domain}}
      CF_APP_NAME: activitiexample
      CF_ROUTE_NAME: activitiexample-dev

- name: manual-deploy-to-prod
  plan:
  - aggregate:
    - get: demo-release
      passed: [acceptance-tests]
    - get: git-repo
      passed: [acceptance-tests]
  - task: deploy-to-prod
    file: git-repo/ci/tasks/cf-deployment.yml
    timeout: 15m
    params:
      API_ENDPOINT: {{cf-prod-api}}
      USERNAME: {{cf-prod-username}}
      PASSWORD: {{cf-prod-password}}
      ORG: {{cf-prod-organization}}
      SPACE: {{cf-prod-space}}
      CF_APPS_DOMAIN: {{cf-prod-domain}}
      CF_APP_NAME: activitiexample
      CF_ROUTE_NAME: activitiexample-prod
